name: gesso
description: A lightweight, chainable terminal styling library for Dart that makes your console output beautiful and expressive with ANSI escape sequences.
version: 1.0.4
publisher: marcomit.it

repository: https://github.com/marcomit/gesso
homepage: https://github.com/marcomit/gesso
documentation: https://pub.dev/documentation/gesso/latest/
issue_tracker: https://github.com/marcomit/gesso/issues

topics:
  - terminal
  - ansi
  - styling
  - console
  - logging

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
