name: gesso
description: A lightweight, chainable terminal styling library for Dart that makes your console output beautiful and expressive with ANSI escape sequences.
version: 1.0.0

repository: https://github.com/yourusername/gesso
homepage: https://github.com/yourusername/gesso
documentation: https://pub.dev/documentation/gesso/latest/
issue_tracker: https://github.com/yourusername/gesso/issues

topics:
  - terminal
  - ansi
  - colors
  - styling
  - console
  - cli
  - logging


environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

